### ISSUE TITLE
Document dependency on BigNumber.h

### ISSUE THREAD

**Issue by alexrj** [italia/cie-PN532#4]
Compilation requires the BigNumber library which I found here:

https://github.com/nickgammon/BigNumber

This dependency should be documented.

**Comment by BrightSoul** [comment]
The BigNumber class wasn't really needed, so I removed its reference from the cie_PN532.h file and documentation is not needed.
BigNumber was used in a previous attempt at performing modular exponentiation without a dedicated chip. The attempt failed on an Arduino UNO due to unsufficient memory (just 2 KBs of SRAM) and I think it won't ever be able to make the calculation needed to verify the CIE is genuine.

CIE verification will be supported only on an Arduino MRK1000 which has dedicated hardware to perform this task in a timely manner. The guys from IPZS are going to update the codebase soon to add this feature.
